error: 
    status - 500 
    message - SyntaxError: Unexpected token } in JSON at position 37
    at JSON.parse (<anonymous>)
    at parse (D:\BridgeLabz\FunDo\fundo-app\node_modules\body-parser\lib\types\json.js:89:19)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:514:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/ 
    method - GET 
    IP - ::1
   {"timestamp":"2024-01-25T06:43:23.413Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected token } in JSON at position 37
    at JSON.parse (<anonymous>)
    at parse (D:\BridgeLabz\FunDo\fundo-app\node_modules\body-parser\lib\types\json.js:89:19)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:514:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users 
    method - GET 
    IP - ::1
   {"timestamp":"2024-01-25T06:43:30.461Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected token } in JSON at position 37
    at JSON.parse (<anonymous>)
    at parse (D:\BridgeLabz\FunDo\fundo-app\node_modules\body-parser\lib\types\json.js:89:19)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:514:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/ 
    method - GET 
    IP - ::1
   {"timestamp":"2024-01-25T06:46:27.470Z"}
error: 
    status - 500 
    message - ObjectParameterError: Parameter "obj" to Document() must be an object, got 65b0b8f7b74c18279ce955e1
    at model.Document (D:\BridgeLabz\FunDo\fundo-app\node_modules\mongoose\lib\document.js:100:11)
    at model.Model (D:\BridgeLabz\FunDo\fundo-app\node_modules\mongoose\lib\model.js:106:12)
    at new model (D:\BridgeLabz\FunDo\fundo-app\node_modules\mongoose\lib\model.js:4919:15)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\mongoose\lib\model.js:3165:22
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\mongoose\lib\model.js:3201:7
    at Array.forEach (<anonymous>)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\mongoose\lib\model.js:3200:15
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\mongoose\lib\helpers\promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (D:\BridgeLabz\FunDo\fundo-app\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (D:\BridgeLabz\FunDo\fundo-app\node_modules\mongoose\lib\index.js:1149:10)
    at Function.create (D:\BridgeLabz\FunDo\fundo-app\node_modules\mongoose\lib\model.js:3135:23)
    at _callee$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:4:27)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.apply (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.signup (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:3:20)
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:28:36)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at apply (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at signup (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:26:20)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:284:15
    at param (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:365:14)
    at param (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:376:14)
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:421:3)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\BridgeLabz\FunDo\fundo-app\node_modules\morgan\index.js:144:5) 
    url - /api/v1/users/65b0b8f7b74c18279ce955e1 
    method - PUT 
    IP - ::1
   {"timestamp":"2024-01-25T07:18:58.531Z"}
error: 
    status - 500 
    message - ObjectParameterError: Parameter "obj" to Document() must be an object, got 65b20b72e7aca70cc0d933a3
    at model.Document (D:\BridgeLabz\FunDo\fundo-app\node_modules\mongoose\lib\document.js:100:11)
    at model.Model (D:\BridgeLabz\FunDo\fundo-app\node_modules\mongoose\lib\model.js:106:12)
    at new model (D:\BridgeLabz\FunDo\fundo-app\node_modules\mongoose\lib\model.js:4919:15)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\mongoose\lib\model.js:3165:22
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\mongoose\lib\model.js:3201:7
    at Array.forEach (<anonymous>)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\mongoose\lib\model.js:3200:15
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\mongoose\lib\helpers\promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (D:\BridgeLabz\FunDo\fundo-app\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (D:\BridgeLabz\FunDo\fundo-app\node_modules\mongoose\lib\index.js:1149:10)
    at Function.create (D:\BridgeLabz\FunDo\fundo-app\node_modules\mongoose\lib\model.js:3135:23)
    at _callee$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:4:27)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.apply (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.signup (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:3:20)
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:28:36)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at apply (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at signup (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:26:20)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:284:15
    at param (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:365:14)
    at param (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:376:14)
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:421:3)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\BridgeLabz\FunDo\fundo-app\node_modules\morgan\index.js:144:5) 
    url - /api/v1/users/65b20b72e7aca70cc0d933a3 
    method - PUT 
    IP - ::1
   {"timestamp":"2024-01-25T07:19:26.045Z"}
error: 
    status - 500 
    message - TypeError: UserService.deleteUser is not a function
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:25:21)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at apply (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at deleteUser (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:23:24)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\BridgeLabz\FunDo\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:514:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/deleteuser 
    method - DELETE 
    IP - ::1
   {"timestamp":"2024-01-25T09:54:53.194Z"}
error: 
    status - 500 
    message - TypeError: UserService.deleteUser is not a function
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:25:21)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at apply (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at deleteUser (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:23:24)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:284:15
    at param (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:365:14)
    at param (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:376:14)
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:421:3)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\BridgeLabz\FunDo\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:514:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/65b23018faa12459546a4035 
    method - DELETE 
    IP - ::1
   {"timestamp":"2024-01-25T09:55:49.050Z"}
error: 
    status - 500 
    message - TypeError: UserService.findOne is not a function
    at _callee4$ (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:57:43)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at apply (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at signin (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:51:20)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\BridgeLabz\FunDo\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:514:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-25T10:20:40.751Z"}
error: 
    status - 500 
    message - TypeError: UserService.findOne is not a function
    at _callee4$ (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:57:43)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at apply (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at signin (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:51:20)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\BridgeLabz\FunDo\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:514:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users//signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-25T10:20:51.205Z"}
error: 
    status - 500 
    message - TypeError: UserService.findOne is not a function
    at _callee4$ (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:57:43)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at apply (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at signin (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:51:20)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\BridgeLabz\FunDo\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:514:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users//signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-25T10:21:18.416Z"}
error: 
    status - 500 
    message - TypeError: UserService.findOne is not a function
    at _callee4$ (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:57:43)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at apply (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at signin (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:51:20)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\BridgeLabz\FunDo\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:514:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-25T10:21:59.566Z"}
error: 
    status - 500 
    message - TypeError: UserService.findOne is not a function
    at _callee4$ (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:57:43)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at apply (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at signin (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:51:20)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\BridgeLabz\FunDo\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:514:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users//signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-25T10:54:30.748Z"}
error: 
    status - 500 
    message - TypeError: UserService.findOne is not a function
    at _callee4$ (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:57:43)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at apply (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at signin (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:51:20)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\BridgeLabz\FunDo\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:514:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users//signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-25T10:55:11.190Z"}
error: 
    status - 500 
    message - TypeError: UserService.findOne is not a function
    at _callee4$ (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:57:43)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at apply (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at signin (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:51:20)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\BridgeLabz\FunDo\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:514:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users//signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-25T10:55:30.102Z"}
error: 
    status - 500 
    message - TypeError: UserService.findOne is not a function
    at _callee4$ (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:57:43)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at apply (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at signin (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:51:20)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\BridgeLabz\FunDo\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:514:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-25T10:55:39.770Z"}
error: 
    status - 500 
    message - ReferenceError: bcrypt is not defined
    at _callee4$ (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:64:5)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at apply (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at signin (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:51:20)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\BridgeLabz\FunDo\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:514:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-25T11:02:44.795Z"}
error: 
    status - 500 
    message - ReferenceError: bcrypt is not defined
    at _callee4$ (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:62:63)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-25T11:10:01.988Z"}
error: 
    status - 500 
    message - ReferenceError: bcrypt is not defined
    at _callee4$ (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:62:63)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-25T11:20:09.273Z"}
error: 
    status - 500 
    message - TypeError: UserService.deleteUser is not a function
    at _callee4$ (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:55:23)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at apply (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at signin (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:52:20)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\BridgeLabz\FunDo\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:514:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-25T11:57:10.379Z"}
error: 
    status - 500 
    message - TypeError: UserService.deleteUser is not a function
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:55:23)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at apply (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at signin (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:52:20)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\BridgeLabz\FunDo\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:514:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-25T11:58:21.525Z"}
error: 
    status - 500 
    message - TypeError: UserService.deleteUser is not a function
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:55:23)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at apply (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at signin (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:52:20)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\BridgeLabz\FunDo\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:514:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-25T11:58:25.589Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'Email')
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:11:11)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.apply (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.signin (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:10:20)
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:55:23)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at apply (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at signin (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:52:20)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\BridgeLabz\FunDo\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:514:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-25T11:59:13.768Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'Email')
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:11:11)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.apply (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.signin (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:10:20)
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:55:23)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at apply (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at signin (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:52:20)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\BridgeLabz\FunDo\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:514:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-25T12:00:02.564Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'Email')
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:12:11)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.apply (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.signin (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:10:20)
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:55:23)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at apply (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at signin (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:52:20)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\BridgeLabz\FunDo\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (D:\BridgeLabz\FunDo\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\BridgeLabz\FunDo\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:514:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-25T12:00:55.829Z"}
error: 
    status - 500 
    message - ReferenceError: data is not defined
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\controllers\/user.controller.js:58:13)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-25T12:02:03.331Z"}
error: 
    status - 500 
    message - ReferenceError: data is not defined
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:22:14)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T05:08:07.704Z"}
error: 
    status - 500 
    message - Error: Invalid Email
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:17:11)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T05:12:21.763Z"}
error: 
    status - 500 
    message - Error: Invalid Password
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:20:13)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T05:12:30.328Z"}
error: 
    status - 500 
    message - Error: Invalid Password
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:20:13)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T05:15:20.570Z"}
error: 
    status - 500 
    message - Error: Invalid Email
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:17:11)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T05:15:29.028Z"}
error: 
    status - 500 
    message - Error: Invalid Email
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:17:11)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T05:39:52.824Z"}
error: 
    status - 500 
    message - Error: Invalid Password
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:20:13)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T05:40:35.267Z"}
error: 
    status - 500 
    message - Error: Invalid Email
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:17:11)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/signup 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T05:42:08.233Z"}
error: 
    status - 500 
    message - Error: Invalid Email
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:17:11)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users//signup 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T05:42:33.452Z"}
error: 
    status - 500 
    message - Error: User already exist!
    at _callee$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:10:11)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users//signup 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T07:32:57.833Z"}
error: 
    status - 500 
    message - Error: User already exist with same Email!
    at _callee$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:10:11)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users//signup 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T07:35:45.653Z"}
error: 
    status - 500 
    message - Error: User already exist with same Email!
    at _callee$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:10:11)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users//signup 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T07:38:10.230Z"}
error: 
    status - 500 
    message - ReferenceError: bcryet is not defined
    at _callee$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:14:26)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users//signup 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T09:31:44.217Z"}
error: 
    status - 500 
    message - TypeError: (0 , _bcrypt.default) is not a function
    at _callee$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:16:40)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users//signup 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T09:48:45.067Z"}
error: 
    status - 500 
    message - Error: User already exist with same Email!
    at _callee$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:12:11)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users//signup 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T09:54:12.476Z"}
error: 
    status - 500 
    message - Error: Invalid Password
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:33:13)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users//signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T09:56:09.223Z"}
error: 
    status - 500 
    message - Error: Invalid Password
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:33:13)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users//signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T09:56:32.128Z"}
error: 
    status - 500 
    message - Error: User already exist with same Email!
    at _callee$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:12:11)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users//signup 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T09:57:34.620Z"}
error: 
    status - 500 
    message - Error: Invalid Password
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:33:13)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users//signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T09:57:38.964Z"}
error: 
    status - 500 
    message - Error: Invalid Password
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:33:13)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T10:04:30.415Z"}
error: 
    status - 500 
    message - Error: Invalid Password
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:33:13)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T10:04:59.512Z"}
error: 
    status - 500 
    message - ReferenceError: user is not defined
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:32:60)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T10:14:10.745Z"}
error: 
    status - 500 
    message - ReferenceError: user is not defined
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:32:60)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T10:15:07.945Z"}
error: 
    status - 500 
    message - Error: Invalid Email
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:30:11)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T10:15:20.607Z"}
error: 
    status - 500 
    message - ReferenceError: user is not defined
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:32:60)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T10:15:39.808Z"}
error: 
    status - 500 
    message - ReferenceError: user is not defined
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:32:60)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T10:16:12.139Z"}
error: 
    status - 500 
    message - Error: data and hash must be strings
    at Object.compare (D:\BridgeLabz\FunDo\fundo-app\node_modules\bcrypt\bcrypt.js:215:17)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (D:\BridgeLabz\FunDo\fundo-app\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (D:\BridgeLabz\FunDo\fundo-app\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:32:42)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T10:17:33.120Z"}
error: 
    status - 500 
    message - Error: data and hash must be strings
    at Object.compare (D:\BridgeLabz\FunDo\fundo-app\node_modules\bcrypt\bcrypt.js:215:17)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (D:\BridgeLabz\FunDo\fundo-app\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (D:\BridgeLabz\FunDo\fundo-app\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:33:42)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T10:20:51.063Z"}
error: 
    status - 500 
    message - Error: data and hash must be strings
    at Object.compare (D:\BridgeLabz\FunDo\fundo-app\node_modules\bcrypt\bcrypt.js:215:17)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (D:\BridgeLabz\FunDo\fundo-app\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (D:\BridgeLabz\FunDo\fundo-app\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:33:42)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T10:21:17.237Z"}
error: 
    status - 500 
    message - Error: data and hash must be strings
    at Object.compare (D:\BridgeLabz\FunDo\fundo-app\node_modules\bcrypt\bcrypt.js:215:17)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (D:\BridgeLabz\FunDo\fundo-app\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (D:\BridgeLabz\FunDo\fundo-app\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:33:42)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T10:21:46.266Z"}
error: 
    status - 500 
    message - Error: data and hash must be strings
    at Object.compare (D:\BridgeLabz\FunDo\fundo-app\node_modules\bcrypt\bcrypt.js:215:17)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (D:\BridgeLabz\FunDo\fundo-app\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (D:\BridgeLabz\FunDo\fundo-app\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:33:42)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T10:22:48.064Z"}
error: 
    status - 500 
    message - Error: Invalid Password
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:36:13)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T10:25:11.670Z"}
error: 
    status - 500 
    message - ReferenceError: chackEmail is not defined
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:38:14)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T10:30:15.644Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (D:\BridgeLabz\FunDo\fundo-app\node_modules\bcrypt\bcrypt.js:208:17)
    at D:\BridgeLabz\FunDo\fundo-app\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (D:\BridgeLabz\FunDo\fundo-app\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (D:\BridgeLabz\FunDo\fundo-app\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:33:42)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T10:32:22.849Z"}
error: 
    status - 500 
    message - Error: Invalid Password
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:36:13)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T10:36:59.479Z"}
error: 
    status - 500 
    message - ReferenceError: chackEmail is not defined
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:37:14)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users//signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T10:41:20.897Z"}
error: 
    status - 500 
    message - Error: Invalid Email
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:28:11)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users//signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T10:59:41.875Z"}
error: 
    status - 500 
    message - Error: Invalid Password
    at _callee2$ (D:\BridgeLabz\FunDo\fundo-app\src\services\/user.service.js:33:13)
    at tryCatch (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\BridgeLabz\FunDo\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users//signin 
    method - POST 
    IP - ::1
   {"timestamp":"2024-01-29T10:59:53.241Z"}
